### ISSUE TITLE
Support for npgsql 5?

### ISSUE THREAD

**Issue by Worble** [SeppPenner/SerilogSinkForPostgreSQL#18]
I've just updated to the latest version of npgsql, and the following error is logged by serilog for the postgresql sink:
```
Exception while emitting periodic batch from Serilog.Sinks.PostgreSQL.PostgreSqlSink: 
System.MissingMethodException:
Method not found: 'Void Npgsql.NpgsqlBinaryImporter.Complete()'.
at Serilog.Sinks.PostgreSQL.PostgreSqlSink.ProcessEventsByCopyCommand(IEnumerable`1 events, NpgsqlConnection connection)
at Serilog.Sinks.PostgreSQL.PostgreSqlSink.EmitBatch(IEnumerable`1 events)
at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.EmitBatchAsync(IEnumerable`1 events)
at Serilog.Sinks.PeriodicBatching.PeriodicBatchingSink.OnTick()
```

**Comment by SeppPenner** [comment]
Hi, thank you for the stack trace first of all 👍 

I have updated the sink to use Npgsql 5, can you check with version 3.1.0 again once it's available?

Sorry for the issue, I have a problem with my PgAdmin instance and cannot really test it on my database right now... 😢

**Comment by Worble** [comment]
Works perfectly, thanks for the quick update 👍

**Comment by SeppPenner** [comment]
Just for reference / documentation reasons: Fixed with https://github.com/SeppPenner/SerilogSinkForPostgreSQL/commit/707f80fe64017e68f5a0a928d7bc9a1b5e4bc86d.
